---
- name: Update and upgrade apt packages
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 86400 # Only run "update_cache=yes" if the last one is more than one day

- name: Install package
  become: yes
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - nmon #Usefule tool to monitor network/proc/memory/filesytem
      - wget
      - libnm-glib-dev
- name: test
  nmcli:
    ctype: ethernet
    name: my-eth1
    ifname: '*'
    state: present

- name: configure name servers
  net_system:
    name_servers:
      - 8.8.8.8
      - 8.8.4.4
