---
- name: Installing snap
  become: true
  register: installation
  apt:
    pkg: snap
    state: latest

- name: Installing microk8s with snap
  become: true
  command: snap install microk8s --classic
  register: installation

- name: Enables microk8s dns dashboard ingress
  shell: source ~/.zshrc && microk8s.enable dns dashboard ingress
  args:
    executable: /bin/zsh
  when: installation is success
