---
- name: Installing Zsh and git
  become: true
  apt:
    pkg: zsh,git
    state: latest
  register: installation

- name: Backing up existing ~/.zshrc
  shell: if [ -f ~/.zshrc ]; then mv ~/.zshrc ~/.zshrc.orig}; fi
  when: installation is success
  sudo: no

- name: Active Zsh
  shell: chsh -s $(which zsh)
  when: installation is success
  become: true

- name: Cloning oh-my-zsh
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh
    dest=~/.oh-my-zsh
  when: installation is success
  register: cloning
  sudo: no

- name: Creating new ~/.zshrc
  copy:
    src=~/.oh-my-zsh/templates/zshrc.zsh-template
    dest=~/.zshrc
  when: cloning is success
  sudo: no
