---
- name: Installing Zsh and git
  apt: pkg=zsh,git state=latest
  register: installation

- name: Backing up existing ~/.zshrc
  shell: if [ -f ~/.zshrc ]; then mv  ~/.zshrc ~/.zshrc.orig; fi
  when: installation is success

- name: Cloning  oh-my-zsh
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh
    dest=~/.oh-my-zsh
  when: installation is success
  register: cloning

- name: Creating new ~/.zshrc
  copy:
    src=zshrc
    dest=~/.zshrc
  when: cloning is success

